name: bgug
description: Break Guns Using Gems!
version: 0.4.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../flame
  json_annotation: 2.0.0
  shared_preferences: 0.4.1
  firebase_admob: 0.7.0
  play_games: 0.3.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/skins/asimov.png
    - assets/images/skins/archer.png
    - assets/images/skins/astronaut.png
    - assets/images/skins/bunny.png
    - assets/images/skins/cat.png
    - assets/images/skins/chef.png
    - assets/images/skins/clown.png
    - assets/images/skins/cop.png
    - assets/images/skins/cowboy.png
    - assets/images/skins/firefighter.png
    - assets/images/skins/gentleman.png
    - assets/images/skins/gold.png
    - assets/images/skins/monk.png
    - assets/images/skins/pirate.png
    - assets/images/skins/santa.png
    - assets/images/skins/viking.png
    - assets/images/skins/wizard.png
    - assets/images/skins/vampire.png
    - assets/images/skins/explorer.png
    - assets/images/skins/egg-bot.png
    - assets/images/skins/the-chosen.png
    - assets/images/skins/reaper.png
    - assets/images/skins/marathonist.png
    - assets/images/skins/jumping.png
    - assets/images/skins/ghost.png
    - assets/images/skins/crusader-knight.png
    - assets/images/skins/alien.png
    - assets/images/skins/cow.png
    - assets/images/skins/t-rex.png
    - assets/images/skins/zeus.png
    - assets/images/hud_bg.png
    - assets/images/base_bottom.png
    - assets/images/base_top.png
    - assets/images/block.png
    - assets/images/obstacle.png
    - assets/images/shooter.png
    - assets/images/bullet.png
    - assets/images/gem.png
    - assets/images/coin.png
    - assets/images/lock.png
    - assets/images/bg.png
    - assets/images/button.png
    - assets/images/endgame_bg.png
    - assets/images/endgame_buttons.png
    - assets/images/tutorial.png
    - assets/images/tutorial-2.png
    - assets/images/splash_screen.png
    - assets/images/google-play-button.png
    - assets/images/username-panel.png
    - assets/images/store/skins_panel.png
    - assets/images/store/store_button.png
    - assets/images/store/store-ui.png
    - assets/images/store/times_2_panel.png
    - assets/images/store/x2coins-certificate.png
    - assets/audio/death.wav
    - assets/audio/gem_collect.wav
    - assets/audio/jump.wav
    - assets/audio/laser_load.wav
    - assets/audio/laser_shoot.wav
    - assets/audio/music.wav
    - assets/store-skins.json
  fonts:
    - family: 5x5
      fonts:
        - asset: assets/fonts/5x5_pixel.ttf
    - family: Blox2
      fonts:
        - asset: assets/fonts/blox2.ttf
    - family: Squared Display
      fonts:
        - asset: assets/fonts/squared_display.ttf
